### ISSUE TITLE
Compliance Dashboard filtering by team member name

### ISSUE THREAD

**Issue by shwecchajain** [adarshmadrecha/jamku#100]
Suggested by `Amit Bhojasiya` (Amit Kumar Bhojasiya & Co)

## Current
Compliance Dashboard filtering options are 
1. Only My
2. My Team
3. All

## Feature
Team member name wise filtering wherein the owner could see the compliance dashboard for each team member

**Comment by yogeshkudikala** [comment]
This was release in `v-3.9.1`
