### ISSUE TITLE
Add date of birth of client in client list

### ISSUE THREAD

**Issue by darshanamhaske** [adarshmadrecha/jamku#13]
`suggested by: Gaurav Kanudawala`

## Problem
currently, there is no way to identify which client birthday today.  

## Feature 
Add date of birth of client in client list

**Comment by darshanamhaske** [comment]
along with the date of birth also show Age of the client for easy identification of seniority for Income tax purpose.

**Comment by adarshmadrecha** [comment]
In the latest version of `Jamku 2`, we have a Calendar report, which shows the client's who's birthday is on a particular date.

However, the same is not yet implemented in Jamku 3. Hence will keep this issue open until the same is added to Jamku 3.

**Comment by adarshmadrecha** [comment]
Date of birth can be seen in the Client List in `Table` view. This was implemented in `v3.10.2`
