### ISSUE TITLE
Time trck view in calender like time line view

### ISSUE THREAD

**Issue by taxtreat** [adarshmadrecha/jamku#137]
It will help to plan according to specific time line and to plan the day according to slots.

**Comment by adarshmadrecha** [comment]
Jamku's most granular planning currently is at "Day" level.
You can set `Target Date` for Task 
Basis target date, you can visualise the plan using "Task Planning" Report.

Feel free to add your counter-argument or calling any of the support team for further discussion on this.

**Comment by adarshmadrecha** [comment]
Something based on below lines can be planned for the Daily Dashboard which will help to visualise the workdone if it is captured with "Start Time" & "End Time"

![image](https://user-images.githubusercontent.com/11911938/79231339-88d99d80-7e83-11ea-8c5d-ce06af38b3df.png)

**Comment by taxtreat** [comment]
Yes definitely is this available in jamku.app?

**Comment by adarshmadrecha** [comment]
We have taken up development for this feature. Once it is released, will comment here, to let you know. FYI: It will be added in "Daily Dashboard"

**Comment by taxtreat** [comment]
Great to have that feature but my intention was that we can also set timing (optinal)  while creating task like we do in  Google calender, it will help to concentrate on  important task where time is defined, else we all are alredy overwhelmed by routine task.

**Comment by adarshmadrecha** [comment]
It was decided in the Design Meeting that, task planning would be done only at Day Level.
Hence, task planning at Hour Level is not possible in Jamku.

**Comment by taxtreat** [comment]
No problem sir, already managed to use it by planning detailed work done,
just putting future time and date its solved my problem.  Thanks.
