### ISSUE TITLE
Access by Group to the client instead of each Client

### ISSUE THREAD

**Issue by BhadreshDoshi** [adarshmadrecha/jamku#150]
You have provided a feature of providing access to the client which is very important. But, instead of providing access to each client separately, there should be an option to provide access for the whole group to the one person. Generally, there is one-point contact for the whole group. So it gives an ease of access to that person from one log-in.

**Comment by adarshmadrecha** [comment]
This feature is already available, simply make the mobile no (in Client Profile) as `Group Visible`
