### ISSUE TITLE
Delete Multiple Tasks

### ISSUE THREAD

**Issue by darshanamhaske** [adarshmadrecha/jamku#16]
`Suggested By: Vyshnavi Varma, Ashok Podugu & Co`

## Feature 
Quickly delete multiple tasks in one click

**Comment by darshanamhaske** [comment]
`suggested by: Sagar Devgadiga `

# Feature

Suggestion: Visitor Register

**Comment by adarshmadrecha** [comment]
Implemented in `v3.9.3`
