### ISSUE TITLE
Client Id - Duplicate records in Client Id should not be allowed

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#173]
in Client ID column, duplicate records should not be allowed.

e.g. At present if any Client ID is having a value "C101"
now if new Client is created or Existing Client is edited with Client ID "C101", software would not restrict it to do so.

Software should restrict it to enter same value, if already exists in any other client.

If any office wants to have same id for multiple clients, Developer should provide an option at the level of "Office Config" w.r.t. that if Duplication at the level of Client ID be allowed or not.

**Comment by ssuranaca** [comment]
Strongly recommended and further more such client I'd field must be available at the time of creation of client and it must shows last 5 client I'd created for information which help us to create next new Client I'd.

**Comment by adarshmadrecha** [comment]
Released in version `3.16.x`
