### ISSUE TITLE
Option to Disallow Duplicate Records in Custom Field values at the level of Tasks related to a Service

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#174]
Custom Fields definition at the level of Services, there should be an option that duplicate values should not be allowed in that field.

e.g. a field has been defined as "Controlling No. / Folder Ref" for a type of task, now this controlling no. should be unique and can't been duplicated, therefore at the the time of defining a field, it should restrict entry of duplicate values. A marking should allowed to be marked.

![1](https://user-images.githubusercontent.com/61269589/80813028-db86b980-8be6-11ea-866a-d222e699e72f.png)
![2](https://user-images.githubusercontent.com/61269589/80813030-dcb7e680-8be6-11ea-9140-659123416416.png)

**Comment by adarshmadrecha** [comment]
This would be a nice to have feature.

**Comment by adarshmadrecha** [comment]
Implemented in `v3.17.0`
