### ISSUE TITLE
Employee Expense (out of pocket Exp by Emp) reimbursement module

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#175]
A new module for expense reimbursement for the expense incurred by the employee on behalf of office.

It should cover following - 

1. Expense submission to Office
2. Approval by competent team leader or authority (which my be decided by admin that who is allowed to approve)
3. It should specially take care for the conveyance kind of expense. Further a standard kind of expense should be inbuilt or allowed to made by user e.g.
Train Pass (one occurrence for a month)
as and when basis travelling expense to Department or travelling, which should say went from this place to this which involved travelling by Train costing INR x and other type of travel INR y amount.

and other things around this may be envisaged.

**Comment by adarshmadrecha** [comment]
Same as #133
