### ISSUE TITLE
Formatted Office Bulletin

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#179]
Suggested by `Bhadresh Doshi`

## Feature Request
Allow formatting the office bulletin 
1. Bold / Italics
2. Multilines
3. Clickable Links

**Comment by adarshmadrecha** [comment]
Released in `v3.14.0`

**Comment by vatsalbhatia** [comment]
It should allow Coloring of Fonts as well

**Comment by adarshmadrecha** [comment]
@vatsalbhatia, this is not supported in current technology stack.
