### ISSUE TITLE
Option to put estimated hrs for each task 

### ISSUE THREAD

**Issue by shwecchajain** [adarshmadrecha/jamku#18]
## Problem
Currently, there is no option to enter estimated hours the Task will take to complete.

## Feature
Currently, there is only option to enter estimated Task Standard Cost

**Comment by adarshmadrecha** [comment]
Implemented in `v3.11.0`
Also, the same can be edited in 2 ways
1. Task View > Billing Tab
2. Task Costing > Double Click on "Estimated Hours" column
