### ISSUE TITLE
Reset search keyword when menu is closed

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#185]
Suggested by `Harsh Vardhan`

## Current Issue
when a search query is typed, the menu is filtered. Then the menu closes the search query is saved. This causes users to first delete the entered query and navigate to other menu.
This cases few extra key strokes for navigation

## Feature Request
When the menu is closed, remove the search query.

**Comment by HarshVardhan84** [comment]
I believe, It shall increase productivity time. Ideally a person goes to a menu for hopping on a different page, then no point first delete the last searched each and everytime.

**Comment by adarshmadrecha** [comment]
Implemented in `v3.14.1`
