### ISSUE TITLE
Stage Master to include a Non-Cummulative 'Completed' and 'Pending' Shortcut

### ISSUE THREAD

**Issue by G-Kumaran** [adarshmadrecha/jamku#186]
![image](https://user-images.githubusercontent.com/41560543/82206895-a5f00900-9926-11ea-92cc-8fe5e5ce81af.png)

Ability to quickly select tasks pending based on current stage and not on a cummulative basis is required. 
Eg. from above screenshot: Stage(5) and Stage (6) pending tasks are 24 and 35 tasks. But only 11 tasks are effectively pending Stage 6 and completed stage 5. 

A quick selection of this subset is essential for tracking tasks.

**Comment by adarshmadrecha** [comment]
This is available on the same page in tabular format.

**Comment by G-Kumaran** [comment]
Thank you, exploring that table. 
That data is exactly what im looking for.

**Comment by G-Kumaran** [comment]
![image](https://user-images.githubusercontent.com/41560543/82633770-a4219080-9c19-11ea-8084-dbd97ee2bc9c.png)

Table glitching out frequently
