### ISSUE TITLE
Capture location when adding attendance

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#189]
Suggested by `Many Offices`

## Feature Request
Many times team members visit client location for work. In this case, capturing location details would be helpful.

**Comment by adarshmadrecha** [comment]
Dev Note:
Instead of "paid" google maps, can use https://vue2-leaflet.netlify.app/ for free maps

**Comment by ssuranaca** [comment]
It's also help us to track use of software by employees during other than office hours/allowed hours or during he is absent from office.

**Comment by ssuranaca** [comment]
Location track also help admin to track use of software by employees during other than office hours/allowed hours or use during he is absent from office.

**Comment by adarshmadrecha** [comment]
> Location track also help admin to track use of software by employees during other than office hours/allowed hours or use during he is absent from office.

Not planning for this reason @ssuranaca
