### ISSUE TITLE
Copy todo from another task/ sub task

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#192]
## Feature Request
Sometimes, we create big list of todo in a task and we just want to open the todos from that task to another task.
While there a option to create todo-template, sometimes the todos can be client sepcific, hence this feature is required.

## Improvement to the feature
While asking for copy of Todo, ask which todo category to be copied.

**Comment by adarshmadrecha** [comment]
Added in `v3.15.0`
Keeping the feature request open, as current implemetation does not have option to selectively copy Todo based on category

**Comment by yogeshkudikala** [comment]
Implemented in `v3.x`
