### ISSUE TITLE
New notification should pop up even while already logged in

### ISSUE THREAD

**Issue by shwecchajain** [adarshmadrecha/jamku#20]
## Feature
When a new task is added, users should get a notification in Web App. Currently the user gets notifcation only in Mobile App.

**Comment by adarshmadrecha** [comment]
Implemented notification in the web application (Jamku 3) on Chrome, Firefox.

Safari currently does not support notifications. Hence keeping this issue open.

**Comment by adarshmadrecha** [comment]
Except for Safari on Iphone, every where, you get notifications.
