### ISSUE TITLE
Copy Todo from previous period tasks

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#201]
## Feature request
While creating bulk tasks, give option to copy Todo from the previous period.

Nitty Girty:
1. Only copy todo's Description Value
2. Don't copy Remark Value

**Comment by adarshmadrecha** [comment]
Added in `v3.15.0`

**Comment by ssuranaca** [comment]
Same can be done in case of Client

**Comment by adarshmadrecha** [comment]
This is now implemented 

![image](https://user-images.githubusercontent.com/11911938/117531067-450d8500-affe-11eb-898c-9b6dbd20c0ff.png)

![image](https://user-images.githubusercontent.com/11911938/117531052-2dce9780-affe-11eb-8d69-8751e786d51a.png)
