### ISSUE TITLE
Shortcut Module links are not working on Chrome

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#211]
## What is not working
Shortcut Module `local network` links are not working on Chrome Browser

## Reason
Google removed a chrome extension which was used for shortcuts module.

**Comment by adarshmadrecha** [comment]
Development Reference
1. Communication between Extention & Native Desktop Apps https://developer.chrome.com/extensions/nativeMessaging
2.

**Comment by vatsalbhatia** [comment]
Give a tutorial to install it off webstore it would work, I am still using it

**Comment by adarshmadrecha** [comment]
@vatsalbhatia, if you have already installed the extension, it will still work. Only the new users are not able to install the extension. Installing an extension which is not on chrome webstore is perceived as a security risk by many.

**Comment by adarshmadrecha** [comment]
This issue is resolved since Google brought back the plugin.
