### ISSUE TITLE
See Dashboard Calendar basis Due Date or Target Date

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#228]
## Feature Request
CUrrently, the calendar on the Home Page (aka Main Dashbaord) is basis `due date` of the Task.
It would be great to have option to see the same basis `target date`.

**Comment by cadarshan** [comment]
In addition to above in this calendar other filters/field like service, client, team also added it will help to analysis and take action from dashboard. Then more detailed information is required we click from it.

**Comment by adarshmadrecha** [comment]
Launched in `v3.17.0`

@cadarshan, your comment is now in sperate feature request #238
