### ISSUE TITLE
Copy SubTask or Todo Name to Workdone Description 

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#231]
Suggested by `Mohammed`

## 
While adding work done from sub-task, can we have subtask name automatically reflected copied in the description filed?
This will save time

**Comment by cadarshan** [comment]
If possible also plan to track time with click of button instead on remembering and entering manually

**Comment by adarshmadrecha** [comment]
Launched in `v3.16.10`
