### ISSUE TITLE
Tally Integration to Jamku for outstanding amount

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#258]
Suggested by `Ramchandra & Associates`

## Feature Request
Instead of making separate billing portal,
kindly incorporate tally integration with jamku so that all information will be updated from tally to jamku with respect to client outstanding. Then this client outstanding can be shown to the client in client portal.

**Comment by adarshmadrecha** [comment]
## Development Update
We will be bringing 2 fields at client level
1. Outstanding Amount
2. Outstanding as on a date

These fields will then be visible to the client in Client Portal.

**Comment by yogeshkudikala** [comment]
Implemented in `v3.23.0`
