### ISSUE TITLE
Global Client Search

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#269]
Suggested by `Vatsal Bhatia`, `Kalpesh Kochar`

## Feature Request
Add global client search in Jamku header.

**Comment by vatsalbhatia** [comment]
Should Have a drop down eg.

Search in ....


Everything
Client
Task
Profile
Password
Link / Shortcut

Note - When Searching in Client, Should search for Client No., Client ID, Name, Profile, Shortcut, Password and all other fields of Client

**Comment by ssuranaca** [comment]
Its superb and robust feature

**Comment by adarshmadrecha** [comment]
This is now live.
Global Task Search feature is --> https://github.com/adarshmadrecha/jamku/issues/533
