### ISSUE TITLE
While creating bulk tasks in compliance report, it should also ask for creation date

### ISSUE THREAD

**Issue by darshanamhaske** [adarshmadrecha/jamku#28]
`suggested by: Ashok Podgu`

## Problem
when creating tasks of prior dates using compliance report there is no option of putting creation date so by default it takes the date of that day

## Feature

While creating bulk tasks in compliance report, it should also ask for creation date

**Comment by adarshmadrecha** [comment]
Implemneted in `v3.10.x`
