### ISSUE TITLE
Ask for adding compliance while creating a task 

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#283]
Suggested by `Nimish Jain`

## Feature Request
Add compliance while adding the task - 
Include an option to add Compliance while creating a task for a new client – Presently the option to add compliance gets enabled after opening the client details . However, it will be easier just to add the compliance directly while creating the task window.

**Comment by yogeshkudikala** [comment]
Implemented in `v3.18.2`
