### ISSUE TITLE
Restrict adding workdone at same time

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#284]
Suggested by `Nimisha Jain`

## Feature Request
In workdone, there is option to fill `From` and `To` time. But, it allows to create duplicate records. 
For eg: 11 am to 3 pm booked in task 1 and 2 pm to 4 pm booked in task 2. 
So, duplicate records created for 2 pm to 3 pm and hence renders improper profitability for both the tasks.

**Comment by yogeshkudikala** [comment]
Released in `v3.17.10`
