### ISSUE TITLE
Due Date can be  date prior to creation date

### ISSUE THREAD

**Issue by mohdlak** [adarshmadrecha/jamku#290]
In task module due date can be date prior to creation date . the back due date is allowed only if creation date is also coincide or later date. But practically client approach for task after due date that is over due in that circumtances we need to create the task in current date with due date prior to creation date to dipict the clear picture that the client has approcahed after due date and task was overdue at the time of acceptence itself.

**Comment by yogeshkudikala** [comment]
Closing this issue as we `won't fix` this.

**Comment by adarshmadrecha** [comment]
Because of the complexity of the compliance dashboard, this cannot be implemented.
