### ISSUE TITLE
Stuck reason/note should be visible in compliance mode and in Task-list. (without opening task)

### ISSUE THREAD

**Issue by taxtreat** [adarshmadrecha/jamku#295]
When we review the dashboard for stuck task or even all stuck task (by a filter in the task list), each time we have to go to task and see the reason instead if you can manage to get that tab(note) visible right there in the dashboard/task list, it will save time to go in each task and see what is the reason.   Even I would request if we can create a template for reason and just apply it like a label that also can be filtered. (like Stuck from client-side / Stuck due to payment not recd / Stuck bcoz waiting for documents from third party)

**Comment by yogeshkudikala** [comment]
It can be seen in the Table view of `Task List`.

**Comment by taxtreat** [comment]
ok got it ! Thank you.
