### ISSUE TITLE
Hide inactive services in Service List

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#301]
Suggested by `Deepika Khumbojkar`

## Feature Request
Instead of showing all the services just show only active service.
Users if required can view all services.
![image](https://user-images.githubusercontent.com/11911938/94933214-bb398e80-04e7-11eb-8a5c-360b3cf871c5.png)

**Comment by yogeshkudikala** [comment]
Implemented in `v3.18.8`
