### ISSUE TITLE
Home- Dashboard - Calender

### ISSUE THREAD

**Issue by cadeepika** [adarshmadrecha/jamku#309]
Request to add completed tasks in the Calender on that particular date. Which can also be filtered Team memberwise as we can currently go with the going tasks. 
Also on this Calender can we see DOB of Client or Team Member

**Comment by adarshmadrecha** [comment]
DOB of Client or Team Member is shown on Daily Dashboard #310 

Also, the completed tasks are also visible in the Daily Dashboard. 
Hence, no plan to again add it in the Calendar on the Home Page.
