### ISSUE TITLE
Specify HSN for Service for Bill Printing

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#31]
`suggested by : Aekta Shah (Chheda & Punatar)`

## Problem
Currently if we need to print HSN number on the bill, user has to enter the HSN number for every line in the bill. This take a lot of time.

## Feature / Solution
Provide option to add HSN when creating service master. When bill is printed, the HSN is copied from Service Master.

**Comment by darshanamhaske** [comment]
`also requested by : Vishal Kelkar`

**Comment by adarshmadrecha** [comment]
This is implemented
