### ISSUE TITLE
WorkDone Future starts at UTC time, it should start at user's Time Zone time

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#327]
Reported by `Aubrey Saverimuttu`

## Bug
When I try to enter workdone, before 5:30 AM (Sri Lanka) time, Jamku gives error of cannot add workdone in future.

**Comment by adarshmadrecha** [comment]
Dev Note: It will require fixing `workdonevalidation.js` >> Line no 67.

**Comment by shilpa0815** [comment]
fixed in v3.19.2
