### ISSUE TITLE
Show HSN / SAC in Bill Print

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#352]
Suggested by `Abhishek Jain`

## Feature Request
Show HSN / SAC in Bill Print.
This was visible in Jamku 2

**Comment by vatsalbhatia** [comment]
It should be shown only if Entity is GST applicable one, in Jamku 2, it was visible for every entity

**Comment by shilpa0815** [comment]
Released in v3.19.7
