### ISSUE TITLE
Importing Billing Location from client profile

### ISSUE THREAD

**Issue by fortowl** [adarshmadrecha/jamku#358]
Hi, 
We are inputting billing location details in client profile. its difficult to provide billing location to each client again . Please provide a feature to import those details from client profile

**Comment by shwecchajain** [comment]
We have an alternate approach for this which is already present in the software. Our representative will be reaching out to explain the same.

**Comment by shilpa0815** [comment]
Done

**Comment by fortowl** [comment]
This alternative approach you told about , no one contacted me regarding
that
