### ISSUE TITLE
Import Attendance - Excel to Jamku

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#365]
Suggested by `Ramesh Purohit (S. H. GARG & ASSOCIATES)` (Ticket No 3113)

## Feature Request
Import Attendance data in Jamku from Excel

## Comment from Requester
I have come across a feature in Jamku APP which allows the user to upload data in the APP through excel sheet in a specified format. I have to use this feature for uploading attendance data (in a specific situation only) however, as of now; there is no template available for uploading attendance.

**Comment by yogeshkudikala** [comment]
Implemented in `v3.19.11`

**Comment by shgargca** [comment]
Jamku Support Team,

 

Kindly look into the below screenshot. I am trying to upload attendance data but system returns error for staff mobile number, which is already a part of the data provided.

 

 

 



 

                                                            

Thanking You

Regards !

 

Ramesh

Contact: 93236 96221

 



S. H. GARG & ASSOCIATES 
Chartered Accountants

604, Platinum Techno Park,
Behind Raghuleela Mall,
Sector-30A, Vashi,
Navi Mumbai – 400 703.
Telephones: +91-22-6794 0001 (Four Lines)

Mobile Number: +91-98209-15560 / +91-83697-59144

(Between 11.00 a. m. to 7.00 p. m., unless there is emergency)

Email:  <mailto:SHGARGCA@GMAIL.COM> SHGARGCA@GMAIL.COM 
(Please mail on the above ID only)

'LET'S HELP THE INDUSTRY TO BE MORE COMPLIANT'
