### ISSUE TITLE
All Bill Locations exportable or editable and Power Query Compatible + Fixing Bulk Update Billing Location through Data Import Tab

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#370]
All Bill Locations should be exportable or editable and Power Query Compatible
plus
Bulk Update Billing Location in Data Import tab and no data within it is visible, how it is supposed to be edited..

1. We are not getting any list while downloading template.
2. There is no place wherefrom I can export all the bill locations.

even if update billing location gets updated, it is requested to pl provide Power query compatibility for this.

**Comment by adarshmadrecha** [comment]
## Development Notes
1. template download should contain data
2. Add bill location in integration
