### ISSUE TITLE
Folder movement from one Client to another

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#376]
We practically store documents of a group clients in one file untill it does not have as many docs to seperate those with a new file.

Therefore while storing these documents in a particular file, we come across a scenerio where one file is to be moved from one client to another i.e to be marked as this file is now for Client B instead of Client A

To do this real life situation is a no issue but implementing it into Jamku i.e to mark this file from Client A to Client B is impossible without deleting.

If we delete we loose all the records of changes in File location, therefore deleting is not recommended, therefore request is to allow shifting a Folder from one client to another be allowed.

However it must not create any database integrity issues....

on careful look at data storing mechanism, we see that each folder is given a unique no. to it, and a seperate column is given there stating the client no. to which it is linked.

So it can be inferred that this is possible to shift it from one Client to another based on database schema, therefore pl allow this.

**Comment by adarshmadrecha** [comment]
![image](https://user-images.githubusercontent.com/11911938/141329998-0890cc78-9668-4ddf-81b1-8b413e049560.png)
