### ISSUE TITLE
Stage Info In Report

### ISSUE THREAD

**Issue by jithinav** [adarshmadrecha/jamku#382]
Can we have a column in Tasklist>Task View which shows at which stage the task currently stays.

**Comment by adarshmadrecha** [comment]
If you click on Progress Bar in Task Row, it will show the Stages.

![task row](https://user-images.githubusercontent.com/11911938/107840818-e7d9ad00-6ddb-11eb-9e4f-8f6af52d11e6.png)

Like This
![Stages](https://user-images.githubusercontent.com/11911938/107840824-fd4ed700-6ddb-11eb-867f-965e74aa8a45.png)

**Comment by adarshmadrecha** [comment]
If we add a Column in the Task List for the stages, it will slow down the Task List.
However, if you still want the column, you can create a custom report for the same.
We can also help you with creation of custom report.

**Comment by jithinav** [comment]
We would love to have that custom report then. I know that we will get stages in progress bar. But our issue is we would like to know how many tasks are there in each stage. Say for example, how many tasks are there in pending Partners approval, or Finalization or verification (Stages mentioned in the image). That is important to know the progress at a glance when we have a number of clients.
