### ISSUE TITLE
Posted or Not Filter in Bill List

### ISSUE THREAD

**Issue by jithinav** [adarshmadrecha/jamku#383]
There is a button in bill generation screen "Posted". Can we have a filter for this in Bill list whether posted or not.

**Comment by shilpa0815** [comment]
Fixed in `v3.19.14`

**Comment by jithinav** [comment]
Thanks for the quick response. Now in table view we have a column for posted or not. But from table view, we can't navigate to bill. Bill Number column is not a link. Can we have an option for that too?

**Comment by shilpa0815** [comment]
Yes, you will get in next update On 12-Feb-2021 2:59 pm, jithinav <notifications@github.com> wrote:
Thanks for the quick response. Now in table view we have a column for posted or not. But from table view, we can't navigate to bill. Bill Number column is not a link. Can we have an option for that too?
