### ISSUE TITLE
Don't allow modifying Out Time in Attendance for past Days. 

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#386]
Reported in: https://github.com/adarshmadrecha/jamku/issues/366#issuecomment-774105465

The Current functionality does not restrict any user from changing the Out time for any past date. It only prevents the user from adding past attendance prior to the number of days configured. 

Request you to kindly check it at your end as well and get it fixed on a high priority basis considering the impact.

Thanking You, Regards !
Ramesh Purohit
S. H. GARG & ASSOCIATES 
Chartered Accountants

**Comment by shilpa0815** [comment]
Fixed in `v3.19.15`

**Comment by shgargca** [comment]
Perfect !!

Working fine now .

Thanking You

Regards !

 

Ramesh Purohit

Contact: 93236 96221

 



S. H. GARG & ASSOCIATES 
Chartered Accountants

604, Platinum Techno Park,
Behind Raghuleela Mall,
Sector-30A, Vashi,
Navi Mumbai – 400 703.
Telephones: +91-22-6794 0001 (Four Lines)

Mobile Number: +91-98209-15560 / +91-83697-59144

(Between 11.00 a. m. to 7.00 p. m., unless there is emergency)

Email:  <mailto:SHGARGCA@GMAIL.COM> SHGARGCA@GMAIL.COM 
(Please mail on the above ID only)

'LET'S HELP THE INDUSTRY TO BE MORE COMPLIANT'

**Comment by shgargca** [comment]
Hi Jamku Support Team,

 

Module: Attendance [Category Setup]

 

There are 5 Attendance categories that I have setup as of now viz. 

OFFICE, HOME, CLIENT PLACE, LEAVE, HOLIDAY. 

 

It often happens that user skips to select the attendance category and just clocks the In Out time, which then needs to be deleted and marked again. To avoid this scenario, is it possible to have a default category during creation or any other possible way?

 

Thanking You

Regards !

 

Ramesh

Contact: 93236 96221

 



S. H. GARG & ASSOCIATES 
Chartered Accountants

604, Platinum Techno Park,
Behind Raghuleela Mall,
Sector-30A, Vashi,
Navi Mumbai – 400 703.
Telephones: +91-22-6794 0001 (Four Lines)

Mobile Number: +91-98209-15560 / +91-83697-59144

(Between 11.00 a. m. to 7.00 p. m., unless there is emergency)

Email:  <mailto:SHGARGCA@GMAIL.COM> SHGARGCA@GMAIL.COM 
(Please mail on the above ID only)

'LET'S HELP THE INDUSTRY TO BE MORE COMPLIANT'

 

From: RAMESH PUROHIT <shgargca@gmail.com> 
Sent: 19 February 2021 05:14 PM
To: 'adarshmadrecha/jamku' <reply@reply.github.com>; 'adarshmadrecha/jamku' <jamku@noreply.github.com>
Cc: 'Subscribed' <subscribed@noreply.github.com>
Subject: RE: [adarshmadrecha/jamku] Don't allow modifying Out Time in Attendance for past Days. (#386)

 

Perfect !!

Working fine now .

Thanking You

Regards !

 

Ramesh Purohit

Contact: 93236 96221

 



S. H. GARG & ASSOCIATES 
Chartered Accountants

604, Platinum Techno Park,
Behind Raghuleela Mall,
Sector-30A, Vashi,
Navi Mumbai – 400 703.
Telephones: +91-22-6794 0001 (Four Lines)

Mobile Number: +91-98209-15560 / +91-83697-59144

(Between 11.00 a. m. to 7.00 p. m., unless there is emergency)

Email:  <mailto:SHGARGCA@GMAIL.COM> SHGARGCA@GMAIL.COM 
(Please mail on the above ID only)

'LET'S HELP THE INDUSTRY TO BE MORE COMPLIANT'
