### ISSUE TITLE
Billing Related

### ISSUE THREAD

**Issue by ALALegal** [adarshmadrecha/jamku#392]
There are two teams- One is Associate and another is Accounts team.

Associate team wants to intimate Accounts regarding the task billing with amount and description. In one task, there are generally 3-5 stages of billing, for example, fees for drafting, fees for 1st hearing, fees for 2nd hearing etc.

1. Money/ Billing permission to Associate
Associate team wants to intimate the Accounts team the complete billing details including billing description and amount. He should be able to intimate for billing and track the billing status without having the billing and money related permission. 

2. Associate should be able to track the stages of billing corresponding to a particular task. 

3. Accounts team should have access to a dash board which enables them to see the billing intimation given by Associate, i.e. to see in respect of which bills intimation have been received and to bill the same. 
4. Billing number should be changed once we cancel the old bill and issue a new bill (being latest date or partial amount). This should also be seen in the report (showing cancelled bill with remarks- cancelled, as also the new bill)

**Comment by adarshmadrecha** [comment]
As discussed on the call.
Closing this request.
