### ISSUE TITLE
Mobile App for ios / iphone

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#4]
## Problem
There is only a mobile app for Andriod Phones. 

## Feature
Create a mobile app for IOS/iphone

**Comment by siddharthjain1** [comment]
Wanted

**Comment by adarshmadrecha** [comment]
Update: The iOS app is almost ready. Will be submitted to the app store for listing this week.

**Comment by adarshmadrecha** [comment]
✔iOS app launched.

Watch this video on how to install on your iPhone
https://www.youtube.com/watch?v=zshcRCFpJDg
