### ISSUE TITLE
Task Name2 and client name should be allowed to fetch in billing lines, at present it is not

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#408]
"Additional Columns in below tables" section of the Bill edit page     
is visible to show which columns to be shown on unbilled tasks and billed   task table          

Now here it should be showing one more column named task name 2 in Billed task table which at present not showing,           

Further a checkbox be allowed which will decide whether taskname2 shall go into billing lines or not           

This checkbox selection should not get reset after next visit

as explained to Yogesh

**Comment by adarshmadrecha** [comment]
## Development Notes
Provide option to add Task Name 2 in billing Description.
This option is stored in Browser Locally, so that users don't need to select the option again and again.

**Comment by vatsalbhatia** [comment]
Request would be to add this "check" to get stored in database so that for that bill, any user or from any PC if you wish to generate bill, it would give same result.

**Comment by yogeshkudikala** [comment]
Also add Client name option
