### ISSUE TITLE
Issue in Mail

### ISSUE THREAD

**Issue by capostwal** [adarshmadrecha/jamku#425]
Subject is not getting Fetched from Mail Template while creating Mail from Template

**Comment by yogeshkudikala** [comment]
The issue has been solved in `3.20.2`. Kindly check whether you're using the latest version or not also check if the subject is present for the template by visiting `Office Config -> Email -> Email Template` .

**Comment by yogeshkudikala** [comment]
Closing the issue as it was solved in `v3.20.2`
