### ISSUE TITLE
Add Team Member filter in Reminder Card on Home Screen

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#447]
Suggested by `Kalpesh Kochar`

## Feature Request
![image](https://user-images.githubusercontent.com/11911938/112059780-4dab1880-8b82-11eb-99d4-e1edf89c1361.png)

**Comment by adarshmadrecha** [comment]
Dev Notes:
1. Can reduce the width of the Filter text box
2. Add search based select box near filter to filter based on team member

**Comment by yogeshkudikala** [comment]
Use solo for filter box
