### ISSUE TITLE
Reminder auto Deleted when Deleting Client

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#47]
`Bug Reported by: Abhishek Jain`

## Problem
If a client has reminder added to it, it automatically gets deleted when the client is deleted.

## Expected Behaviour
The user should not be allowed to delete a client if there are reminders assigned to the client. The users should get an error say, there are reminders assigned to the client. (Similar to what we have for Task currently)

**Comment by yogeshkudikala** [comment]
This bug is fixed in version 0.8.4
