### ISSUE TITLE
Password at Client Page in tabular format

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#470]
Password at client page should be allowed an option to be shown in tabular format...

at present it is not available

Plus in tabular format it must show a pencil icon for editing from there only... for editing it should not force user to switch back to card view

**Comment by adarshmadrecha** [comment]
The card view has option to hide the password. Password is only visible on Hover.
Moreover, the username and password can be quickly be copied to the clipboard by simply clicking on it.

![image](https://user-images.githubusercontent.com/11911938/115135606-597de380-a037-11eb-91d4-ba6f78996a16.png)

All these functionalities cannot be replicated in Table View.

The most critical is the ability to hide the password by default. As many of the times, team members use Jamku when clients are around. Hence, the passwords should be hidden by default as a security feature.

**Comment by vatsalbhatia** [comment]
It is not supposed to remove existing card view....

Expectation is to provide table view as well, in addition to current view..... also for above stated purposes, default view could be set to card view (current view, this will ensure currrent copy and hiding features)

so that some features of table view such as multi column filter could be used.... at client or group level.....
