### ISSUE TITLE
Folder Lists at Client Page - Add Scroll Bar

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#473]

**Comment by adarshmadrecha** [comment]
We have "View All" button in the "Folder" card in Client View.
This takes you to the "Folder List" (filtered to this specific client).
In this Folder List, we have option to view the list in Table Format.


![image](https://user-images.githubusercontent.com/11911938/115135508-a1503b00-a036-11eb-9f78-d8eeb88f7132.png)

**Comment by vatsalbhatia** [comment]
Pl fix the size of Folder Tab, it we have too many Folders in this View All button goes at the end of the page.

**Comment by adarshmadrecha** [comment]
## Development Note
We can add a max height to the Folder List.
So, if there are more than say 5 Items in the folder, it will show a scroll bar.
This way the "View All" footer does not go to be very bottom.
