### ISSUE TITLE
Document Module Reports

### ISSUE THREAD

**Issue by cadeepika** [adarshmadrecha/jamku#483]
Few Reports are required in Document Module like
1. Client Documents Returnable pending with us
2. Our Documents Returnable pending with Client

Also if possible signature of Client to whom documents are handed over should be captured in Jamku Document List.

**Comment by adarshmadrecha** [comment]
## Development Note
1. Add "Is Returned" filter

**Comment by adarshmadrecha** [comment]
@cadeepika 
for Point No 2 
> Our Documents Returnable pending with Client

This can be managed used Outward Category?
