### ISSUE TITLE
Pl allow 2 decimal figures in tbamt column, as of no decminal figures can be entered

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#493]

**Comment by adarshmadrecha** [comment]
My personal View: Tracking this value in paise terms does not makes sense.

**Comment by vatsalbhatia** [comment]
This field is not equal to "Expected Cost" as the title says, this field means Charging made to customer for this task. 

You might be inferring above conclusion based on "Expected Cost" parameter, but actually it is being used as Charge for that task....

Further as I believe everywhere, wherever amount is referred, even in Jamku, it always gets denominated in figures upto 2 decimals and that is how any amount is denominated.

even if anybody wants to use it without decimals, how this addon (I am using the word addon but it is a very basic feature) will hamper him from using as he is using as of now, then why restrict this update.

Further let me show you a practical scenerio, I have paid INR 20000.50 for a tax payment, I want to charge him my fees plus this amount. Guide me how to do that and I would like to draw your attention to the thing, that matching it with tally or bill amount, we are doing mechanically, as in with a logic that this should be equal to that, otherwise for minor difference, it will throw an error, 

Pl bring this ASAP, it would be feasible in very little development time.
