### ISSUE TITLE
Add Team in Task costing 

### ISSUE THREAD

**Issue by cadeepika** [adarshmadrecha/jamku#495]
Add column of Team members in Task Costing page

**Comment by adarshmadrecha** [comment]
Please elaborate on this.
What's the problem it fixes?
How is this information utilised?

**Comment by cadeepika** [comment]
While issuing bills to clients such lists are segregated managerwise to
managers so that we we also know which manager has done how much work

Regards,
For Kedar Kumbhojkar and Company
Chartered Accountants


CA Deepika Kumbhojkar
Partner
Mobile no  9881491659
