### ISSUE TITLE
In rare cases, the Task Name is picked up wrong for a selected service

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#501]
We have identified a bug where the Task Name does not match with the Service name.
This is being investigated.

**Comment by yogeshkudikala** [comment]
Alternative solution -> 
While creating a single service based task
the Task name passed from frontend should be same as service name based on officeid and serviceid... if not then an error is thrown

**Comment by adarshmadrecha** [comment]
This had been fixed in `v3.23.1`
