### ISSUE TITLE
Issue about Start Date of Compliance

### ISSUE THREAD

**Issue by capostwal** [adarshmadrecha/jamku#516]
When Compliance s created, if I put start date 01/04/21 It should not appear in Compliance Calendar under Non Compliances for the period before April 21, but it still shows Task not created in March21

**Comment by adarshmadrecha** [comment]
It's a limitation of the Compliance Dashboard.
Will be working on fixing this.

**Comment by capostwal** [comment]
Ok

*With Warm Regards,*
 CA Pritesh Ostwal
+91 95-03-390009

THORAT OSTWAL & ASSOCIATES
Chartered Accountants
*Pune Office :*425/46, "Vishwas", 1st Floor,
TMV Colony, Opp Katariya Highschool
Mukund Nagar, Pune - 411037.
Tel: 020-24264664

*Raigad Office :*Pitambar Bunglow,
Near N M Joshi Vidyabhavan, Goregaon
Tal Mangaon, Raigad - 402103.
 The information contained in this communication is intended solely for the
use of the individual or entity to whom it is addressed and others
authorized to receive it.It may contain confidential or legally privileged
information. If you are not the intended recipient you are hereby notified
that any disclosure, copying, distribution or taking any action in reliance
on the contents of this information is strictly prohibited and may be
unlawful. If you have received this communication  in error, please notify
us immediately by responding to this email and then delete it from your
system. Thorat Ostwal and Associates is neither liable for the proper and
complete transmission of the information contained in this communication
nor for any delay in its receipt.

**Comment by adarshmadrecha** [comment]
this is fixed in `v3.24.2`, using new scheduler module.
