### ISSUE TITLE
Expenses

### ISSUE THREAD

**Issue by jithinav** [adarshmadrecha/jamku#525]
Hi,

We have two option to link an expense, either to task or client. Many of the cases we would prefer to attach it to a task, but then in the expense list client name is not coming. Since that particular task is associated to a client, it would be better if it gets automatically attached to a client also and show in the expense list.
![Jamku Expense List issue](https://user-images.githubusercontent.com/78638740/117407685-85043780-af2c-11eb-9806-d2b68ff7e9b7.jpg)

**Comment by adarshmadrecha** [comment]
I agree, the Client Name should be visible.
This is a bug. We shall fix it in next update.
