### ISSUE TITLE
List of Compliance ID

### ISSUE THREAD

**Issue by jithinav** [adarshmadrecha/jamku#526]
Can we have an option to get client level compliance IDs? It is useful for bulk compliance update.

**Comment by adarshmadrecha** [comment]
The compliance table can be downloaded from Service List > Service View > Compliance Tab.
This excel (csv) contains compliance ID for bulk updation.

![image](https://user-images.githubusercontent.com/11911938/117527173-a37b3900-afe7-11eb-9d34-cac1e46de8d8.png)
