### ISSUE TITLE
Pl Provide Data Import Template for Service Fields Updation 

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#528]

**Comment by shilpa0815** [comment]
This is already implemented 
Visit `ServiceList` page `Download Fields Template` 

![servicefiels](https://user-images.githubusercontent.com/70199061/119934481-78ab5180-bfa3-11eb-9806-f922cebf0e10.PNG)

Visit `Import Data` page select Service Field Update and follow the regular steps

![service](https://user-images.githubusercontent.com/70199061/119934645-be681a00-bfa3-11eb-9106-d4fff9f9c4fe.PNG)
