### ISSUE TITLE
Calendar Report- Profit Center, Team member filter

### ISSUE THREAD

**Issue by yogeshkudikala** [adarshmadrecha/jamku#53]
Suggested by: `Dharmesh Thakkar`,`Richa Nagda`

## Feature
1. Calendar report  should have Profit Center 
1. Calendar report should have Team member filter option.

**Comment by adarshmadrecha** [comment]
1. Since the clicking on the count opens task list, which has `Profit Center` option, we don't need this feature
2. Report filter will solve this feature request
