### ISSUE TITLE
Task Edit Template does not allow Task Name 2 to be beyond 50 characters

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#547]

**Comment by yogeshkudikala** [comment]
Task name 2 can be maximum 50 characters

**Comment by vatsalbhatia** [comment]
Pl see in the attached snap, it is already more than 50 characters, My query is it is possible to add more than 50 char in GUI but not possible to add same while importing

![image](https://user-images.githubusercontent.com/61269589/119225831-dd8a2600-bb23-11eb-8fe0-0b271046e9d9.png)
