### ISSUE TITLE
Task Edit throws an error message while updating some tasks.

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#548]
Task Edit throws an error message - 

Creation Date cannot be before 2000 days in past

why it does not even allow editing ??

**Comment by adarshmadrecha** [comment]
Did you enter creation date before 2000 days than today?
Or this error is thrown erroneously?

**Comment by vatsalbhatia** [comment]
Yes it was date before 2000 days from today, but why Jamku is interested to control this aspect...
This is simply a thing on which user should have control over....
Further even if Jamku do not want to add or create record that back (not user friendly although, Jamku has no business to tell me by what time you can update, it can give a control in Ofiice Config saying, these many days back you can create / edit from Data Import Tab) , then atleast do not restrict editing for already created tasks, we are just getting locked.

**Comment by yogeshkudikala** [comment]
In this version it's made 5000
