### ISSUE TITLE
Pl give an option to bulk update Category, Profit Center and Cost Center of Tasks in GUI

### ISSUE THREAD

**Issue by vatsalbhatia** [adarshmadrecha/jamku#551]
Similar to Admin Controls, Label Updation, this option be allowed as well.

**Comment by shilpa0815** [comment]
This is already implemented 
visit `TaskList` click on checkbox of selected task open `UpdateTask` dialogueBox and open the same tab `Category`


![category](https://user-images.githubusercontent.com/70199061/119826490-b3ff3f00-bf15-11eb-8de7-7a4ab49f1e2a.PNG)
