### ISSUE TITLE
Option to update bill-wise amount at client level instead of Total Outstanding Amount

### ISSUE THREAD

**Issue by TulikaKhetan** [adarshmadrecha/jamku#563]
Billing option should also be available at client level. Sometimes, a tentative bill amount is given to the client or a proforma invoice is made before task creation. To keep a record of such bill amount given to the client, an option should be available at client level to maintain bill-wise records along with Total Outstanding Amount. (Accessible by people with "Has Money Permissions" only)

**Comment by adarshmadrecha** [comment]
Let's connect over call to discuss this.

**Comment by TulikaKhetan** [comment]
Please let me know when to connect. You can reach me at 80000-84442.



Best Regards,



Tulika Khetan

Partner



S S Singhvi & Associates

p: +91 261 2313030 m: +91 80000 84442

a: Surat | Jodhpur | Mumbai | Navsari | Vapi

***@***.***

w: http://www.singhviadvsors.com














---- On Thu, 03 Jun 2021 16:23:52 +0530 Adarsh Madrecha ***@***.***> wrote ----





Let's connect over call to discuss this.

**Comment by TulikaKhetan** [comment]
Please let me know when to connect. You can reach me at 80000-84442.

**Comment by adarshmadrecha** [comment]
@TulikaKhetan As discussed on call, 

1. Outstanding Amount - It will not be possible to extract this information from any accounitng software. Manually feeding will not be sustainable.
2. Track fees agreed with Client - We are planning #576
