### ISSUE TITLE
Inward Outward Tracking Module

### ISSUE THREAD

**Issue by priyamadrecha** [adarshmadrecha/jamku#8]
## Problem
Offices currently maintain a register or excel file to keep track of what was received from Clients and what was given to Client. This register is not searchable and whenever we have to search anything it takes a lot of time.

## Feature
Jamku should have Inward and Outward tracking module. 
Helps in identifying what all things are still with office and not returned

**Comment by adarshmadrecha** [comment]
Implemented in `v3.18.0`
https://help.jamku.app/changes/202009.html#new-document-module
