### ISSUE TITLE
Show Attendance Info on Calendar

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#85]
## Feature
Attendance can be shown on the calendar when on "My" view.
The dates can be coloured based on present or absent.

**Comment by yogeshkudikala** [comment]
Can implement once vuetify implement this.
https://github.com/vuetifyjs/vuetify/issues/9941

**Comment by adarshmadrecha** [comment]
This feature is launched in `v3.11.2` (Daily Dashboard) and also in Team View > Dashboard Tab
