### ISSUE TITLE
Marking a Stage as completed should automatically update the Task Completed Percentage

### ISSUE THREAD

**Issue by priyamadrecha** [adarshmadrecha/jamku#9]
`suggested by: Kaushal Shah`

## Why
Task Search List shows percentage Completed. Which helps in getting an idea of how is the progress of the Task

## Feature
When a user marks the stage as completed, it will automatically also update the Percentage Completed of that Task.
Say, a task has 4 stages. Then, marking the stage as completed will increase the percentage Completed by 25%

**Comment by adarshmadrecha** [comment]
This feature is introduced in version `0.8.2`
