### ISSUE TITLE
Attendance more granular permission

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#91]
Suggested by `Kajal Soni (Premal Gandhi & Associates)`

## Current
Attendance has only 2 options
1. Yes - Allows that user to mark attendance of all users
1. No - Does not allow users to mark attendance of anyone

## Feature
Add more option in attendance permission
1. Self - Allows the user to only mark his attendance
1. Team - Allows the user to mark his attendance for himself/herself as well as his team.

**Comment by yogeshkudikala** [comment]
this is release in `v-3.9.1`
