### ISSUE TITLE
Show Pie chart of Tasks count based on Service

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#92]
## Feature
To further enhance #88 `Service-wise task count on Dashboard`, add a doughnut/pie chart 

The chart will be based on 2 Options
1. Service
2. Service Type (aka Service Category)

This feature can be further enhanced by allowing users to click on the service type which filters the Service List in the current Dashboard

**Comment by yogeshkudikala** [comment]
this is release in `v-3.9.1`
