### ISSUE TITLE
To add Work Done in bulk

### ISSUE THREAD

**Issue by shwecchajain** [adarshmadrecha/jamku#93]
Suggested by `a team member from Premal Gandhi & Associates`

## Feature
Option should be given to add work done in bulk by selecting multiple tasks.

Problem Statement
Many a times it happens that same type of work is done on multiple tasks and same time is spent so an option to add work done for multiple tasks at one go

**Comment by yogeshkudikala** [comment]
this is release in `v-3.9.1`
